name: Scope Moniter

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Installing tar and unew via binary
      run: |
        sudo apt install unzip -y
        sudo apt install tar
        wget https://github.com/rix4uni/unew/releases/download/v0.0.5/unew-linux-amd64-0.0.5.tgz
        tar -xvzf unew-linux-amd64-0.0.5.tgz
        mv unew /usr/local/bin/unew
        rm -rf unew-linux-amd64-0.0.5.tgz

    - name: Running scope_moniter.sh
      run: |
        bash scope_moniter.sh

