name: Full Scope Scanner

on:
  push:
    paths:
      - 'inscope_*.txt'
      - 'newdata_*.txt'
  workflow_dispatch:

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip jq curl git golang
          
          wget https://github.com/projectdiscovery/katana/releases/latest/download/katana_amd64.zip
          unzip katana_amd64.zip -d /usr/local/bin/

          echo "export PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
          echo "$HOME/go/bin" >> $GITHUB_PATH

          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/tomnomnom/waybackurls@latest

      - name: 📁 Make Scripts Executable
        run: chmod +x scripts/*.sh

      - name: 📊 Run Recon
        run: scripts/recon.sh

      - name: ⚔️ Run ZAP Full Scan
        run: scripts/zap_scan.sh

      - name: ⚡ Run Nuclei Scan
        run: scripts/nuclei_scan.sh

      - name: 🧾 Generate Markdown Report
        run: scripts/generate_report.sh

      - name: 📢 Send Discord Notification
        run: scripts/upload_discord.sh

      - name: ✅ Git Commit & Push
        run: scripts/git_push_changes.sh

