name: Full Scope Scanner

on:
  push:
    paths:
      - 'inscope_*.txt'
      - 'newdata_*.txt'
  workflow_dispatch:

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Dependencies
        run: |
          # 🔁 Refresh and install core tools
          sudo apt update -y
          sudo apt install -y zip curl wget git gnupg lsb-release software-properties-common
          
          # 🧠 Install Go
          sudo apt install -y golang

          # 🧭 Add Google Chrome (for headless browser tools)
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update -y
          sudo apt install -y google-chrome-stable

          # ✅ Setup Go path and install tools
          echo "export PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
          echo "$HOME/go/bin" >> $GITHUB_PATH

          CGO_ENABLED=1 go install github.com/projectdiscovery/katana/cmd/katana@latest
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/tomnomnom/waybackurls@latest

      - name: 📁 Make Scripts Executable
        run: chmod +x scripts/*.sh

      - name: 📊 Run Recon
        run: scripts/recon.sh

      - name: ⚔️ Run ZAP Full Scan
        run: scripts/zap_scan.sh

      - name: ⚡ Run Nuclei Scan
        run: scripts/nuclei_scan.sh

      - name: 🧾 Generate Markdown Report
        run: scripts/generate_report.sh

      - name: 📢 Send Discord Notification
        run: scripts/upload_discord.sh

      - name: ✅ Git Commit & Push
        run: scripts/git_push_changes.sh
        
      - name: 📁 Ensure Directories Exist
        run: |
          mkdir -p recon_output scans logs reports
          touch scans/history.log

      - name: 📂 Check Required Files
        run: |
          ls data/Domains/inscope_domains.txt data/NewData/newdata_inscope_domains.txt || echo "⚠️ Missing scope files!"
